- name: Build Debug APK
  run: |
    set -o pipefail
    gradle :app:assembleDebug --stacktrace --info --warning-mode all --no-daemon | tee build.log

- name: Upload build log
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: build-log
    path: build.log

- name: Upload APK artifact
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: QuickCutAI-debug-apk
    path: app/build/outputs/apk/debug/*.apk
